name: Windows MSVC FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msvc_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - win64
          - x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build FFmpeg /w MSVC toolset
        run: |
          #dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64"
          #dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX64\ARM64"
          git clone https://github.com/FFmpeg/FFmpeg -b release/4.4
          cd FFmpeg
          dir .
          echo "INFO: Configuring FFmpeg for Windows with ./configure --target-os=win64 --arch=${{matrix.arch}} --toolchain=msvc"
          configure --target-os=win64 --arch=${{ matrix.arch }} --toolchain=msvc
          #dir ffbuild
          #Get-Content ffbuild\config.log
          #make
          #make install
    
