name: Windows MSVC FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msvc_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64_x86
          - amd64_arm64
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build FFmpeg /w MSVC toolset
        run: |
          dir C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64
          dir C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.34.31933\bin\HostX64\ARM64
          where cl
          where link
          #git clone https://github.com/FFmpeg/FFmpeg -b release/4.4
          #cd FFmpeg
          #./configure --target-os=win64 --arch=x86_64 --toolchain=msvc
          #dir ffbuild
          #Get-Content ffbuild\config.log
          #make
          #make install
    
