name: Windows MSYS2 FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msys2_ffmpeg_build.yml
env:
  DPDK_VERSION: 23.03
  MSYS: winjitdebug
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64, arch: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install FFmpeg & IMTL Packages
        uses: msys2/setup-msys2@v2.17.0
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            make:p
            cmake:p
            diffutils:p
            yasm:p
            nasm:p
            SDL:p
            SDL2:p
            SDL2_ttf:p
            toolchain:p
            libx264:p
            binutils:p
            ffnvcodec-headers:p
            libva:p
            clang:p
            x264:p
            openssl:p
            gcc:p
            meson:p
            pkg-config:p
            json-c:p
            libpcap:p
            dlfcn:p
      - name: Install tools
        run: |
          wget https://nmap.org/npcap/dist/npcap-sdk-1.12.zip
          unzip -d npcap-sdk npcap-sdk-1.12.zip
          cp npcap-sdk/Lib/x64/* $MSYSTEM_PREFIX/lib/
          
          # Remove mman-win32 build for now!
          #git clone https://github.com/alitrack/mman-win32
          #cd mman-win32
          #./configure --prefix=$MSYSTEM_PREFIX
          #make & make install
          
      - name: Checkout IMTL repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        
      - name: Checkout DPDK repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: 'DPDK/dpdk'
          ref: v${{ env.DPDK_VERSION }}
          path: dpdk
          
      - name: Checkout FFMPEG repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: 'FFmpeg/FFmpeg'
          ref: release/4.4
          path: FFmpeg
       
      - name: Checkout Cisco H264
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: 'cisco/openh264'
          ref: openh264v2.3.1
          path: openh264
          
      - name: Build FFmpeg
        run: |
          env | sort
          echo "##########################################################################################################"
          echo "#                     Performing Widnows FFmpeg customizations build /w MSYS2                            #"
          echo "##########################################################################################################"
          echo "Build will be perform in ${HOME} on FFmpeg release 4.4"
          echo "INFO: Checkout repo on runner workspace"
          pwd
          ls -al
          cd $HOME
          mkdir -p ${HOME}/ffmpeg
          
          # Fixes in https://sourceforge.net/p/mingw-w64/mailman/message/29053757/
          cp -f /mingw64/bin/ar.exe /mingw64/bin/x86_64-w64-mingw32-ar.exe
          cp -f /mingw64/bin/strip.exe /mingw64/bin/x86_64-w64-mingw32-strip.exe
          cp -f /mingw64/bin/nm.exe /mingw64/bin/x86_64-w64-mingw32-nm.exe
          cp -f /mingw64/bin/dlltool.exe /mingw64/bin/x86_64-w64-mingw32-dlltool.exe
          cp -f /mingw64/bin/windres.exe /mingw64/bin/x86_64-w64-mingw32-windres.exe
          ls -al /mingw64/bin

          gcc --version
          #git clone https://github.com/FFmpeg/FFmpeg.git -b release/4.4
          #cd FFmpeg
          ##./configure --arch=x86_64 --target-os=mingw64 --cross-prefix=x86_64-w64-mingw64-
          #./configure --arch=${{matrix.env}} --target-os=${{matrix.sys}} --cross-prefix=${{matrix.arch}}-w64-mingw32- --prefix=${HOME}/ffmpeg --enable-shared --disable-lto --disable-w32threads --enable-gpl --enable-libx264 #--enable-libopenh264 --enable-encoder=libopenh264
          #make -j$(nproc)
          #make install
          
          #cat ffbuild/config.log
          #tar -cvzf ffmpeg-mingw64-bin.tgz $HOME/ffmpeg/bin
          #ls -al $HOME/ffmpeg/bin
          
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: Release FFmpeg v4.4 Cross Compile Mingw64 64-bit Binaries
      #    path: $HOME/ffmpeg/ffmpeg-mingw64-bin.tgz
         
