name: Windows MSYS2 FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msys2_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw32, env: x86, arch: i686 }
          - { sys: mingw64, env: x86_64, arch: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install FFmpeg Packages
        uses: msys2/setup-msys2@v2.17.0
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            make:p
            cmake:p
            meson:p
            diffutils:p
            yasm:p
            nasm:p
            SDL:p
            SDL2:p
            gcc:p
            toolchain:p
            libx264:p
            pkg-config:p
      - name: Build FFmpeg
        run: |
          env | sort
          echo "##########################################################################################################"
          echo "#                     Performing Widnows FFmpeg customizations build /w MSYS2                            #"
          echo "##########################################################################################################"
          echo "Build will be perform in ${HOME} on FFmpeg release 4.4"
          cd $HOME
          gcc --version
          git clone https://github.com/FFmpeg/FFmpeg.git -b release/4.4
          cd FFmpeg
          ./configure --arch=${{matrix.env}} --target-os=${{matrix.sys}} --cross-prefix=${{matrix.arch}}-w64-${{matrix.sys}}- --enable-shared --disable-lto --disable-w32threads
          make -j$(nproc)
          make install
          ls -al /usr/local
          #./configure --arch=x86_64 --target-os=mingw64 --cross-prefix=x86_64-w64-mingw64-
          cat ffbuild/config.log
          
          #./configure --enable-static --enable-gpl --disable-w32threads --disable-autodetect --enable-debug
         
