name: Windows MSYS2 FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msys2_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64, arch: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install FFmpeg & IMTL Packages
        uses: msys2/setup-msys2@v2.17.0
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            make:p
            cmake:p
            diffutils:p
            yasm:p
            nasm:p
            SDL:p
            SDL2:p
            SDL2_ttf:p
            toolchain:p
            libx264:p
            binutils:p
            ffnvcodec-headers:p
            libva:p
            clang:p
            x264:p
            openssl:p
            gcc:p
            meson:p
            pkg-config:p
            json-c:p
            libpcap:p
            dlfcn:p
      - name: Install tools
        run: |
          wget https://nmap.org/npcap/dist/npcap-sdk-1.12.zip
          unzip -d npcap-sdk npcap-sdk-1.12.zip
          cp npcap-sdk/Lib/x64/* $MSYSTEM_PREFIX/lib/
          git clone https://github.com/alitrack/mman-win32
          cd mman-win32
          ./configure --prefix=$MSYSTEM_PREFIX
          make & make install
          
      - name: Checkout DPDK repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: 'DPDK/dpdk'
          ref: v${{ env.DPDK_VERSION }}
          path: dpdk
          
      - name: Checkout FFMPEG repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: 'FFmpeg/FFmpeg'
          ref: release/4.4
          path: FFmpeg
          
      - name: Build FFmpeg
        run: |
          env | sort
          echo "##########################################################################################################"
          echo "#                     Performing Widnows FFmpeg customizations build /w MSYS2                            #"
          echo "##########################################################################################################"
          echo "Build will be perform in ${HOME} on FFmpeg release 4.4"
          ls -al
          cd $HOME
          mkdir -p ${HOME}/ffmpeg
          # Fixes in https://sourceforge.net/p/mingw-w64/mailman/message/29053757/
          cp -f /mingw64/bin/ar.exe /mingw64/bin/x86_64-w64-mingw32-ar.exe
          cp -f /mingw64/bin/strip.exe /mingw64/bin/x86_64-w64-mingw32-strip.exe
          cp -f /mingw64/bin/nm.exe /mingw64/bin/x86_64-w64-mingw32-nm.exe
          cp -f /mingw64/bin/dlltool.exe /mingw64/bin/x86_64-w64-mingw32-dlltool.exe
          cp -f /mingw64/bin/windres.exe /mingw64/bin/x86_64-w64-mingw32-windres.exe
          ls -al /mingw64/bin
          # Downgrade gcc from 13 to 8.2.2.1
          #yes | pacman -U https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gc-8.2.2-1-any.pkg.tar.zst
          gcc --version
          git clone https://github.com/FFmpeg/FFmpeg.git -b release/4.4
          cd FFmpeg
          ./configure --arch=${{matrix.env}} --target-os=${{matrix.sys}} --cross-prefix=${{matrix.arch}}-w64-mingw32- --prefix=${HOME}/ffmpeg --enable-shared --disable-lto --disable-w32threads --enable-gpl --enable-libx264
          make -j$(nproc)
          make install
          ls -al /usr/local
          #./configure --arch=x86_64 --target-os=mingw64 --cross-prefix=x86_64-w64-mingw64-
          cat ffbuild/config.log
          tar -cvzf ffmpeg-mingw64-bin.tgz $HOME/ffmpeg/bin
          ls -al $HOME/ffmpeg/bin
          #./configure --enable-static --enable-gpl --disable-w32threads --disable-autodetect --enable-debug
          
      - uses: actions/upload-artifact@v3
        with:
          name: Release FFmpeg v4.4 Cross Compile Mingw64 64-bit Binaries
          path: $HOME/ffmpeg/ffmpeg-mingw64-bin.tgz
         
