name: Windows MSYS2 FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msys2_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install FFmpeg Packages
        uses: msys2/setup-msys2@v2.17.0
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            make:p
            cmake:p
            meson:p
            diffutils:p
            yasm:p
            SDL:p
            gcc:p
            toolchain:p
            libx264:p
            pkg-config:p
      - name: Build FFmpeg
        run: |
          env | sort
          cd $HOME
          git clone https://github.com/FFmpeg/FFmpeg.git -b release/4.4
          cd FFmpeg
          ./configure --arch=${{ matrix.env }} --target-os=${{ matrix.sys }} --cross-prefix=${{ matrix.env }}-w64-${{ matrix.sys }}- --enable-static --enable-nonfree          
          #./configure --enable-shared --disable-static --enable-debug
          ls -al
          cat ffbuild/config.log
