name: Windows MSYS2 FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msys2_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw32, env: i686 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install FFmpeg Packages
        uses: msys2/setup-msys2@v2.17.0
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            make:p
            diffutils:p
            yasm:p
            SDL:p
            gcc:p
            libx264:p
            pkg-config:p
      - name: Build FFmpeg
        run: |
          rm -f arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi.zip
          wget https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/12.2.mpacbti-rel1/binrel/arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi.zip
          unzip -o arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi.zip
          cd arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi/bin
          export PATH=$PWD/arm-none-eabi-:$PATH
          export CROSS_COMPILE=$PWD/arm-none-eabi-
          arm-none-eabi-gcc --version
          
          git clone https://github.com/FFmpeg/FFmpeg.git -b release/4.4
          cd FFmpeg
          ./configure --arch=armel --target-os=${{matrix.sys}} --cross-compile=${CROSS_COMPILE} --enable-static --enable-nonfree
          
