name: Windows MSYS2 FFmpeg build
on:
  push:
    paths:
      - .github/workflows/msys2_ffmpeg_build.yml
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - { sys: mingw64, env: x86_64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install FFmpeg Packages
        uses: msys2/setup-msys2@v2.17.0
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            base-devel
            unzip
          pacboy: >-
            make:p
            cmake:p
            meson:p
            diffutils:p
            yasm:p
            SDL:p
            gcc:p
            toolchain:p
            libx264:p
            pkg-config:p
      - name: Build FFmpeg
        run: |
          env | sort
          cd $HOME
          which gcc
          which link

          git clone https://github.com/FFmpeg/FFmpeg.git -b release/4.4
          cd FFmpeg
          #ls -al /var/cache/pacman/pkg
          ./configure --arch=${{ matrix.env }} --target-os=win64 --enable-static --enable-gpl --disable-w32threads       
          #./configure --enable-static --enable-gpl --disable-w32threads --disable-autodetect --enable-debug
          #cat ffbuild/config.log
